name: ardilla
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  gap: ^3.0.0
  get_it: ^7.6.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  injectable: ^2.1.1
  # injectable: ^1.5.3
  internet_connection_checker: ^1.0.0+1
  logger: ^1.3.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

